artifact_location: file:///home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/229712802633426649
creation_time: 1763147390499
experiment_id: '229712802633426649'
last_update_time: 1763147390499
lifecycle_stage: active
name: close_gain_forecasting
