creation_timestamp: 1763448441614
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1763448441614
model_id: null
name: stock_predictor_spark_rf_unified_5stocks
run_id: 4498d6bb4ffe4ec6bdcbd9a7c238957c
run_link: null
source: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/260892442739248592/4498d6bb4ffe4ec6bdcbd9a7c238957c/artifacts/model
status: READY
status_message: null
storage_location: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/260892442739248592/4498d6bb4ffe4ec6bdcbd9a7c238957c/artifacts/model
user_id: null
version: 8
