artifact_uri: file:///home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/659928479284864024/1610a79c28c6475f99c2338fd56a0fb5/artifacts
end_time: 1763565229696
entry_point_name: ''
experiment_id: '659928479284864024'
lifecycle_stage: active
run_id: 1610a79c28c6475f99c2338fd56a0fb5
run_name: spark_gbt_unified_monitoring_AAL-AAPL-ABBV-AMD-AMGN-BABA-BIIB-CMCSA-CMG-COP_20251119_202241
source_name: ''
source_type: 4
source_version: ''
start_time: 1763563962036
status: 3
tags: []
user_id: mha2cob
