artifact_uri: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/702925934234739188/bedf632088c741eeb8fcb6fa135f1877/artifacts
end_time: 1763385083065
entry_point_name: ''
experiment_id: '702925934234739188'
lifecycle_stage: active
run_id: bedf632088c741eeb8fcb6fa135f1877
run_name: unified_model_monitoring_AAPL-GOOG-TSLA_20251117_184122
source_name: ''
source_type: 4
source_version: ''
start_time: 1763385083035
status: 4
tags: []
user_id: mha2cob
