creation_timestamp: 1763537840631
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1763537840631
model_id: null
name: stock_predictor_spark_rf_unified_5stocks
run_id: e1c2495de3084c62aa9af8f885baae6e
run_link: null
source: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/260892442739248592/e1c2495de3084c62aa9af8f885baae6e/artifacts/model
status: READY
status_message: null
storage_location: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/260892442739248592/e1c2495de3084c62aa9af8f885baae6e/artifacts/model
user_id: null
version: 12
