artifact_uri: file:///home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/229712802633426649/3fbd452f3c9c4acc8dcb53f818cf4191/artifacts
end_time: 1763390259876
entry_point_name: ''
experiment_id: '229712802633426649'
lifecycle_stage: active
run_id: 3fbd452f3c9c4acc8dcb53f818cf4191
run_name: unified_model_monitoring_AAPL_20251117_200705
source_name: ''
source_type: 4
source_version: ''
start_time: 1763390225158
status: 3
tags: []
user_id: mha2cob
