artifact_uri: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/974964133641391798/f5d8444b161f44b5a5fdbafe573cd6bb/artifacts
end_time: 1763559034817
entry_point_name: ''
experiment_id: '974964133641391798'
lifecycle_stage: active
run_id: f5d8444b161f44b5a5fdbafe573cd6bb
run_name: scalability_monitoring_20251119_190034
source_name: ''
source_type: 4
source_version: ''
start_time: 1763559034776
status: 3
tags: []
user_id: mha2cob
