artifact_location: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/artifacts/stock_prediction_experiments
creation_time: 1762671549722
experiment_id: '104621710198221799'
last_update_time: 1762671549722
lifecycle_stage: active
name: stock_prediction_experiments
