artifact_uri: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/260892442739248592/e1c2495de3084c62aa9af8f885baae6e/artifacts
end_time: 1763537848377
entry_point_name: ''
experiment_id: '260892442739248592'
lifecycle_stage: active
run_id: e1c2495de3084c62aa9af8f885baae6e
run_name: spark_rf_distributed_monitoring_AAL-AAPL-ABBV-AMD-AMGN_20251119_130705
source_name: ''
source_type: 4
source_version: ''
start_time: 1763537825819
status: 3
tags: []
user_id: mha2cob
