creation_timestamp: 1763405740726
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1763405740726
model_id: m-ff2842f5ab5440dba5331b27fa3ae2de
name: stock_predictor_hybrid_sklearn_unified_5stocks
run_id: 04e6b012cc9347e982f6b337f9759a43
run_link: null
source: models:/m-ff2842f5ab5440dba5331b27fa3ae2de
status: READY
status_message: null
storage_location: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/974964133641391798/models/m-ff2842f5ab5440dba5331b27fa3ae2de/artifacts
user_id: null
version: 6
