artifact_location: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/676067242327470734
creation_time: 1762799617854
experiment_id: '676067242327470734'
last_update_time: 1762799617854
lifecycle_stage: active
name: test_monitoring
