creation_timestamp: 1763655277100
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1763655277100
model_id: m-86f8d6269c6e42ba990b4c76d2dfa3f2
name: stock_predictor_hybrid_sklearn_unified_29stocks
run_id: 0de2d56fc75b4a5e95baeec9425fd9a3
run_link: null
source: models:/m-86f8d6269c6e42ba990b4c76d2dfa3f2
status: READY
status_message: null
storage_location: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/974964133641391798/models/m-86f8d6269c6e42ba990b4c76d2dfa3f2/artifacts
user_id: null
version: 3
