artifact_uri: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/260892442739248592/bcccd0ea6fa74b3780fd80fb6481b373/artifacts
end_time: 1763401799783
entry_point_name: ''
experiment_id: '260892442739248592'
lifecycle_stage: active
run_id: bcccd0ea6fa74b3780fd80fb6481b373
run_name: spark_rf_distributed_monitoring_AAPL-GOOG-MSFT-NVDA-TSLA_20251117_231941
source_name: ''
source_type: 4
source_version: ''
start_time: 1763401781949
status: 3
tags: []
user_id: mha2cob
