artifact_uri: file:///home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/659928479284864024/8522e7ce78dd4fa89ce03a32e96bc6e7/artifacts
end_time: 1763586576220
entry_point_name: ''
experiment_id: '659928479284864024'
lifecycle_stage: active
run_id: 8522e7ce78dd4fa89ce03a32e96bc6e7
run_name: spark_gbt_unified_monitoring_AAL-AAPL-ABBV-AMD-AMGN-BABA-BIIB-CMCSA-CMG-COP-COST-CRM-CVX-EBAY-GE-GOOG-GSK-MRK-NKE-NVDA-ORCL-PEP-PYPL-QCOM-QQQ-TSLA-TSM-USO-WFC_20251120_000941
source_name: ''
source_type: 4
source_version: ''
start_time: 1763577581099
status: 3
tags: []
user_id: mha2cob
