creation_timestamp: 1762776066509
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1762776066509
model_id: null
name: stock_predictor_unified_5stocks
run_id: 028840bd02f74bc39b3072af6005ed81
run_link: null
source: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/897954263920293505/028840bd02f74bc39b3072af6005ed81/artifacts/model
status: READY
status_message: null
storage_location: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/897954263920293505/028840bd02f74bc39b3072af6005ed81/artifacts/model
user_id: null
version: 3
