artifact_location: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/702925934234739188
creation_time: 1762770435936
experiment_id: '702925934234739188'
last_update_time: 1762770435936
lifecycle_stage: active
name: pipeline_scalability_monitoring
