artifact_location: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/323962559918034896
creation_time: 1763394735544
experiment_id: '323962559918034896'
last_update_time: 1763394735544
lifecycle_stage: active
name: multi_mode_scalability_monitoring
