aliases: {}
creation_timestamp: 1763401856699
deployment_job_id: null
deployment_job_state: null
description: null
last_updated_timestamp: 1763477995142
name: stock_predictor_hybrid_sklearn_unified_5stocks
