artifact_location: file:///home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/682257865880459596
creation_time: 1762672165637
experiment_id: '682257865880459596'
last_update_time: 1762672165637
lifecycle_stage: active
name: stock_forecasting_gbt_exp
