aliases: {}
creation_timestamp: 1763401799741
deployment_job_id: null
deployment_job_state: null
description: null
last_updated_timestamp: 1763461275480
name: stock_predictor_spark_rf_unified_5stocks
