aliases: {}
creation_timestamp: 1763382253152
deployment_job_id: null
deployment_job_state: null
description: null
last_updated_timestamp: 1763384692569
name: stock_predictor_hybrid_AAPL-GOOG-TSLA_xgboost
