artifact_uri: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/260892442739248592/f2268b33dc094bc7a6a2a6d19e9d5423/artifacts
end_time: 1763449216830
entry_point_name: ''
experiment_id: '260892442739248592'
lifecycle_stage: active
run_id: f2268b33dc094bc7a6a2a6d19e9d5423
run_name: spark_rf_distributed_monitoring_AAPL-GOOG-MSFT-NVDA-TSLA_20251118_122948
source_name: ''
source_type: 4
source_version: ''
start_time: 1763449188368
status: 3
tags: []
user_id: mha2cob
