aliases: {}
creation_timestamp: 1763586571657
deployment_job_id: null
deployment_job_state: null
description: null
last_updated_timestamp: 1763675045911
name: stock_predictor_spark_gbt_unified_29stocks
