artifact_location: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/608535781630392078
creation_time: 1763147516590
experiment_id: '608535781630392078'
last_update_time: 1763147516590
lifecycle_stage: active
name: close_gain_forecasting_unified_monitoring
