creation_timestamp: 1763558673837
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1763558673837
model_id: null
name: stock_predictor_spark_gbt_unified_5stocks
run_id: 9b4b488a86044450a07841fc3b4ed91f
run_link: null
source: file:///home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/659928479284864024/9b4b488a86044450a07841fc3b4ed91f/artifacts/model
status: READY
status_message: null
storage_location: file:///home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/659928479284864024/9b4b488a86044450a07841fc3b4ed91f/artifacts/model
user_id: null
version: 7
