creation_timestamp: 1763551574747
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1763551574747
model_id: null
name: stock_predictor_spark_gbt_unified_5stocks
run_id: 4696bb801ca84ce6b1f3d4fe2568d853
run_link: null
source: file:///home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/659928479284864024/4696bb801ca84ce6b1f3d4fe2568d853/artifacts/model
status: READY
status_message: null
storage_location: file:///home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/659928479284864024/4696bb801ca84ce6b1f3d4fe2568d853/artifacts/model
user_id: null
version: 5
