creation_timestamp: 1763385395044
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1763385395044
model_id: null
name: close_gain_forecast_model_gbt
run_id: 6c68f39fb51d4a3eb46d680c66bef470
run_link: null
source: file:///home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/229712802633426649/6c68f39fb51d4a3eb46d680c66bef470/artifacts/model
status: READY
status_message: null
storage_location: file:///home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/229712802633426649/6c68f39fb51d4a3eb46d680c66bef470/artifacts/model
user_id: null
version: 1
