aliases: {}
creation_timestamp: 1763482204924
deployment_job_id: null
deployment_job_state: null
description: null
last_updated_timestamp: 1763482206823
name: stock_predictor_hybrid_sklearn_unified_29stocks
