aliases: {}
creation_timestamp: 1763395645412
deployment_job_id: null
deployment_job_state: null
description: null
last_updated_timestamp: 1763449883357
name: stock_predictor_spark_gbt_unified_5stocks
