creation_timestamp: 1763538749235
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1763538749235
model_id: null
name: stock_predictor_spark_rf_unified_10stocks
run_id: b0df76b34957481dac87a625e2242e22
run_link: null
source: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/260892442739248592/b0df76b34957481dac87a625e2242e22/artifacts/model
status: READY
status_message: null
storage_location: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/260892442739248592/b0df76b34957481dac87a625e2242e22/artifacts/model
user_id: null
version: 1
