creation_timestamp: 1763369766383
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1763369766383
model_id: null
name: stock_predictor_AAPL_GOOG
run_id: 338deb8d8f4a4995916ff55ce7affbc3
run_link: null
source: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/608535781630392078/338deb8d8f4a4995916ff55ce7affbc3/artifacts/model
status: READY
status_message: null
storage_location: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/608535781630392078/338deb8d8f4a4995916ff55ce7affbc3/artifacts/model
user_id: null
version: 14
