artifact_uri: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/974964133641391798/841a6fedecd7421794eaa71b54a3b0c6/artifacts
end_time: 1763406989151
entry_point_name: ''
experiment_id: '974964133641391798'
lifecycle_stage: active
run_id: 841a6fedecd7421794eaa71b54a3b0c6
run_name: hybrid_sklearn_hybrid_monitoring_AAPL-GOOG-MSFT-NVDA-TSLA_20251118_004628
source_name: ''
source_type: 4
source_version: ''
start_time: 1763406988668
status: 4
tags: []
user_id: mha2cob
