artifact_location: file:///home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/934230335871642060
creation_time: 1762683258162
experiment_id: '934230335871642060'
last_update_time: 1762683258162
lifecycle_stage: active
name: stock_forecasting_gbt_exp_unified
