aliases: {}
creation_timestamp: 1763538749229
deployment_job_id: null
deployment_job_state: null
description: null
last_updated_timestamp: 1763538749269
name: stock_predictor_spark_rf_unified_10stocks
