aliases: {}
creation_timestamp: 1763565226077
deployment_job_id: null
deployment_job_state: null
description: null
last_updated_timestamp: 1763565226113
name: stock_predictor_spark_gbt_unified_10stocks
