creation_timestamp: 1763653920597
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1763653920597
model_id: null
name: stock_predictor_spark_rf_unified_29stocks
run_id: e1f0f2de48bf44a4b480188339a731bf
run_link: null
source: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/260892442739248592/e1f0f2de48bf44a4b480188339a731bf/artifacts/model
status: READY
status_message: null
storage_location: /home/mha2cob/Downloads/breaking_data/spark_ml_pipeline/mlflow_tracking/260892442739248592/e1f0f2de48bf44a4b480188339a731bf/artifacts/model
user_id: null
version: 3
